name: Generate .env file
#second try
on:
  push:
    branches:
      - development

jobs:
  generate-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate .env file
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >> .env
      - name: Commit .env file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .env
          git commit -m "Generate .env file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: development
