name: Generate .env file

on:
  push:
    branches:
      - development

jobs:
  generate-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate .env file
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
       run: |
          echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >> .env
      - name: Use the .env file
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Use the API keys from the .env file in your code
          echo "ANTHROPIC_API_KEY: $ANTHROPIC_API_KEY"

