# This workflow will generate a .env file and populate it with  
# the anthropic API key from repository secrets.

name: Generate .env File

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  generate-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" > .env
          echo ".env file generated successfully."

      - name: List files (for debugging)
        run: ls -la

      - name: Use .env file (example)
        run: |
          # Example: Load the .env file and use the API key
          source .env
          echo "API key loaded: $ANTHROPIC_API_KEY"

      - name: Clean up .env file
        # run: rm .env  # Remove the .env file to ensure it's not committed
