name: Generate api_keys.env File

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  generate-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug API Key
        run: |
          if [ -z "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "Error: ANTHROPIC_API_KEY is not set!"
            exit 1
          else
            echo "ANTHROPIC_API_KEY is set."
          fi

      - name: Create api_keys.env file
        run: |
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" > api_keys.env
          sync  # Force filesystem sync
          sleep 1  # Give the filesystem a moment
          ls -la 
          #chmod 644 .env
          echo "api_keys.env file generated successfully."

      - name: Debug before upload
        run: |
          echo "Current directory: $(pwd)"
          find . -name "*.env" -type f
          cat api_keys.env
          
      - name: Upload api_keys.env file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: api_keys.env

      - name: Clean up api_keys.env file
        run: rm api_keys.env  # Remove the .env file to ensure it's not committed
        
